- name: Configure the role vbotka.freebsd_postinstall
  hosts: localhost

  vars:

    tags_path: defaults/main/sanity_tags.yml

  tasks:

    - name: Confirm that you know what you are doing.
      ansible.builtin.assert:
        that: i_know_what_i_am_doing | d(false) | bool
        fail_msg: Confirm that you know what you are doing.

    - name: Create list of all tags fp_sanity_tags in {{ tags_path }}
      when: fp_sanity_tags | d(false) | bool
      block:

        - name: "Find tasks files"
          ansible.builtin.find:
            path: tasks
            recurse: true
            patterns: '*.yml'
          register: out

        - name: "Create list of tasks"
          ansible.builtin.set_fact:
            _tasks: "{{ _tasks + lookup('file', item) | from_yaml }}"
          loop: "{{ out.files | map(attribute='path') }}"
          vars:
            _tasks: []

        - name: "Debug list of tasks"
          ansible.builtin.debug:
            msg: |
              {{ _tasks | to_yaml(indent=2) | indent(2) }}
          when: debug | d(false) | bool

        - name: "Create list of tags"
          ansible.builtin.debug:
            msg: |
              {{ _tags_tasks | to_yaml(indent=2) | indent(2) }}"
              {{ _tags_block | to_yaml(indent=2) | indent(2) }}"
          vars:
            _tags_tasks: "{{ _tasks | json_query('[].tags') | flatten | unique | sort }}"
            _tags_block: "{{ _tasks | json_query('[].block[].tags') | flatten | unique | sort }}"
          when: debug | d(false) | bool

        - name: "Create list of tags"
          ansible.builtin.set_fact:
            _tags: "{{ (_tags_tasks + _tags_block + ['all']) |
                       difference(['always', 'never']) |
                       unique | sort }}"
          loop: "{{ out.files | map(attribute='path') }}"
          vars:
            _tags_tasks: "{{ _tasks | json_query('[].tags') | flatten | unique | sort }}"
            _tags_block: "{{ _tasks | json_query('[].block[].tags') | flatten | unique | sort }}"

        - name: "Debug list of tags"
          ansible.builtin.debug:
            msg: |
              no_of_tags: {{ _tags | length }}
              tags: {{ _tags | to_yaml(indent=2) | indent(2) }}
          when: debug | d(false) | bool

        - name: "Create {{ tags_path }}"
          ansible.builtin.copy:
            dest: "{{ tags_path }}"
            content: |
              fp_sanity_tags:
                {{ _tags | to_nice_yaml(indent=2) | indent(2) }}
