---
- name: "Motd: Configure /etc/motd"
  ansible.builtin.template:
    src: "{{ fp_motd_conf_template }}"
    dest: "{{ fp_motd_conf_file }}"
    mode: "{{ fp_motd_conf_mode }}"
    backup: "{{ fp_backup }}"
  tags: fp_motd_create

- name: "Motd: Set update_motd YES"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*update_motd\s*=(.*)$
    line: update_motd="YES"
    backup: "{{ fp_backup }}"
  when: fp_update_motd | bool
  tags: fp_motd_rcconf

- name: "Motd: Set update_motd NO"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*update_motd\s*=(.*)$
    line: update_motd="NO"
    backup: "{{ fp_backup }}"
  when: not fp_update_motd | bool
  tags: fp_motd_rcconf

# NOTES
# By default system info is added to the top of /etc/motd on reboot.
# Set fp_update_motd=False to disable this update.

# EOF
