---

- name: "mount-iso: Debug fp_mount_iso_debug={{ fp_mount_iso_debug }}"
  vars:
    msg: |-
      fp_mount_iso_points_create: {{ fp_mount_iso_points_create }}
      fp_mount_iso_entries:
        {{ fp_mount_iso_entries | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_mount_iso_debug | bool
  tags: fp_mount_iso_debug

- name: "mount-iso: Import mount-vnode.yml"
  ansible.builtin.import_tasks: mount-vnode.yml
  vars:
    _fp_mount_task: iso
    _fp_mount_fstype_default: cd9660
    _fp_mount_points_create: "{{ fp_mount_iso_points_create }}"
    _fp_mount_entries: "{{ fp_mount_iso_entries }}"
    _fp_mount_debug: "{{ fp_mount_iso_debug }}"

# EOF
...
