---
- name: "Nfs: Debug fp_nfs_debug={{ fp_nfs_debug }}"
  vars:
    msg: |-
      fp_nfs_enable: {{ fp_nfs_enable }}
      fp_nfs_enable_rcconf:
        {{ fp_nfs_enable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_nfs_disable_rcconf:
        {{ fp_nfs_disable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_rpc_lockd_enable: {{ fp_rpc_lockd_enable }}
      fp_rpc_lockd_flags: {{ fp_rpc_lockd_flags }}
      fp_rpc_lockd_enable_rcconf:
        {{ fp_rpc_lockd_enable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_rpc_lockd_disable_rcconf:
        {{ fp_rpc_lockd_disable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_rpc_statd_enable: {{ fp_rpc_statd_enable }}
      fp_rpc_statd_flags: {{ fp_rpc_statd_flags }}
      fp_rpc_statd_enable_rcconf:
        {{ fp_rpc_statd_enable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_rpc_statd_disable_rcconf:
        {{ fp_rpc_statd_disable_rcconf | to_yaml(indent=2) | indent(2) }}
      fp_nfs_service_paths:
        {{ fp_nfs_service_paths | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_nfs_debug | bool
  tags: fp_nfs_debug

  # Note: The module service_facts doesn't work in FreeBSD.
- name: "Nfs: Service state info"
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_bsd_service_facts
    apply:
      tags: fp_nfs_services
  vars:
    al_bsd_service_paths: "{{ fp_nfs_service_paths }}" # noqa: var-naming[no-role-prefix]
  tags: always

  # Note: There is no status option of nfsclient. If needed, restart the
  # service when /var/db/mounttab exists.
- name: "Nfs: Stat /var/db/mounttab"
  ansible.builtin.stat:
    path: /var/db/mounttab
  register: fp_nfs_var_db_mounttab
  tags: fp_nfs_services

- name: Debug
  tags: fp_nfs_services
  when: fp_nfs_debug | bool
  block:

    - name: "Nfs: Debug service state info fp_nfs_debug={{ fp_nfs_debug }}"
      ansible.builtin.debug:
        var: al_ansible_facts_services

    - name: "Nfs: Debug stat /var/db/mounttab fp_nfs_debug={{ fp_nfs_debug }}"
      ansible.builtin.debug:
        var: fp_nfs_var_db_mounttab.stat.exists

    - name: "Nfs: Debug handlers fp_nfs_debug={{ fp_nfs_debug }}"
      ansible.builtin.debug:
        var: fp_nfs_handlers

- name: "Nfs: Enable services"
  ansible.builtin.include_tasks:
    file: fn/rcconf-item.yml
  loop:
    - label: "nfs: Enable and start nfs client"
      conf: "{{ fp_nfs_enable_rcconf }}"
      when: "{{ fp_nfs_enable | bool }}"
      notify: "{{ fp_nfs_handlers.nfsclient }}"
    - label: "nfs: Enable and start lockd"
      conf: "{{ fp_rpc_lockd_enable_rcconf }}"
      when: "{{ fp_rpc_lockd_enable | bool }}"
      notify: "{{ fp_nfs_handlers.lockd }}"
    - label: "nfs: Enable and start statd"
      conf: "{{ fp_rpc_statd_enable_rcconf }}"
      when: "{{ fp_rpc_statd_enable | bool }}"
      notify: "{{ fp_nfs_handlers.statd }}"
  loop_control:
    loop_var: oi
    label: "{{ oi.label }}"
  tags: fp_nfs_enable

- name: "Nfsd: Disable services"
  ansible.builtin.include_tasks:
    file: fn/rcconf-item.yml
  loop:
    - label: "nfs: Disable and stop nfs client"
      conf: "{{ fp_nfs_disable_rcconf }}"
      when: "{{ not fp_nfs_enable | bool }}"
      notify: disable and stop nfs client
    - label: "nfs: Disable and stop lockd"
      conf: "{{ fp_rpc_lockd_disable_rcconf }}"
      when: "{{ not fp_rpc_lockd_enable | bool }}"
      notify: disable and stop lockd
    - label: "nfs: Disable and stop statd"
      conf: "{{ fp_rpc_statd_disable_rcconf }}"
      when: "{{ not fp_rpc_statd_enable | bool }}"
      notify: disable and stop statd
  loop_control:
    loop_var: oi
    label: "{{ oi.label }}"
  tags: fp_nfs_disable

# EOF
