---
- name: "Sanity: Debug fp_sanity_debug={{ fp_sanity_debug }}"
  ansible.builtin.debug:
    msg: |-
      fp_sanity_tags_fatal: {{ fp_sanity_tags_fatal }}
      ansible_run_tags:
        {{ ansible_run_tags | to_yaml(indent=2) | indent(2) }}
      ansible_skip_tags:
        {{ ansible_skip_tags | to_yaml(indent=2) | indent(2) }}
      fp_sanity_tags:
        {{ fp_sanity_tags | to_yaml(indent=2) | indent(2) }}
  when: fp_sanity_debug | bool
  tags: fp_sanity_debug

- name: Tags
  when: fp_sanity_tags_fatal | bool
  tags: fp_sanity_tags
  block:

    - name: "Sanity: Unknown run tags"
      ansible.builtin.fail:
        msg: "[ERR] Unknown run tag(s): {{ _tags_unknown }}"
      vars:
        _tags_unknown: "{{ ansible_run_tags | difference(fp_sanity_tags) }}"
      when:
        - ansible_run_tags | length > 0
        - _tags_unknown | length > 0

    - name: "Sanity: Unknown skip tags"
      ansible.builtin.fail:
        msg: "[ERR] Unknown skip tag(s): {{ _tags_unknown }}"
      vars:
        _tags_unknown: "{{ ansible_skip_tags | difference(fp_sanity_tags) }}"
      when:
        - ansible_skip_tags | length > 0
        - _tags_unknown | length > 0

# EOF
