---
- name: "Sshd: Debug fp_sshd_debug={{ fp_sshd_debug }}"
  when: fp_sshd_debug | bool
  tags: fp_sshd_debug
  vars:
    msg: |-
      fp_sshd_bin: {{ fp_sshd_bin }}
      fp_sshd_conf_file: {{ fp_sshd_conf_file }}
      fp_sshd_conf:
        {{ fp_sshd_conf | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: Configure /etc/rc.conf
  tags: fp_sshd_rcconf
  block:

    - name: "Sshd: Enable and start sshd"
      when: fp_sshd_enable | bool
      notify: enable and start sshd
      ansible.builtin.lineinfile:
        dest: /etc/rc.conf
        regexp: ^\s*sshd_enable\s*=(.*)$
        line: sshd_enable="YES"
        backup: "{{ fp_backup }}"

    - name: "Sshd: Disable and stop sshd"
      when: not fp_sshd_enable | bool
      notify: disable and stop sshd
      ansible.builtin.lineinfile:
        dest: /etc/rc.conf
        regexp: ^\s*sshd_enable\s*=(.*)$
        line: sshd_enable="NO"
        backup: "{{ fp_backup }}"

- name: "Sshd: Configure {{ fp_sshd_conf_file }}"
  tags: fp_sshd_config
  notify: reload sshd
  ansible.builtin.lineinfile:
    dest: "{{ fp_sshd_conf_file }}"
    regexp: ^\s*{{ item.key }}\s+(.*)$
    insertbefore: ^\s*#\s*{{ item.key }}
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ fp_backup }}"
    validate: "{{ fp_sshd_bin }} -t -f %s"
  loop: "{{ fp_sshd_conf }}"

- name: "Sshd: sshd {{ state }}"
  tags: fp_sshd_service
  vars:
    state: "{{ fp_sshd_enable | bool | ternary('started', 'stopped') }}"
  ansible.builtin.service:
    name: sshd
    state: "{{ state }}"

# EOF
