---
- name: "Swap: Debug (fp_swap_debug={{ fp_swap_debug }})"
  vars:
    msg: |-
      fp_swap_enable: {{ fp_swap_enable }}
      fp_swap_file: {{ fp_swap_file | d('UNDEFINED') }}
      fp_swap_md: {{ fp_swap_md | d('UNDEFINED') }}
      fp_swap_size: {{ fp_swap_size | d('UNDEFINED') }}
      fp_swap_stsize: {{ fp_swap_stsize | d('UNDEFINED') }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_swap_debug | bool
  tags: fp_swap_debug

- name: "Swap: Enable swap and add entry in /etc/fstab"
  when: fp_swap_enable | bool
  block:

    - name: "Swap: Create swapfile {{ fp_swap_file }}"
      ansible.builtin.shell:
        cmd: >
          sh -c
          'if [ ! -e {{ fp_swap_file }} ]; then
             printf "create";
          fi'
      register: command_result
      changed_when: command_result.stdout | d('none') == 'create'
      notify: create swap

    - name: "Swap: Create swap entry in /etc/fstab"
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: ^\s*{{ fp_swap_md }}\s+(.*)$
        line: "{{ fp_swap_md }} none swap sw,file={{ fp_swap_file }},late 0 0"
        backup: "{{ fp_backup }}"
      notify: mount swap

    #   - ansible.posix.mount:
    #       name: 'none'
    #       src: "{{ fp_swap_md }}"
    #       fstype: swap
    #       opts: "sw,file={{ fp_swap_file }},late"
    #       passno: '0'
    #       dump: '0'
    #       state: mounted
    #       backup: true
    #
    # Note: ansible.posix.mount module can't mount fstype swap
    # https://github.com/ansible/ansible/pull/49390
    # https://github.com/ansible-collections/ansible.posix/issues/106

    - name: "Swap: Change swapfile {{ fp_swap_file }}"
      ansible.builtin.shell:
        cmd: >
          sh -c
          'if [ -e {{ fp_swap_file }} ] &&
          [ "`stat -f %z {{ fp_swap_file }}`" -ne "{{ fp_swap_stsize }}" ]; then
             printf "change";
          fi'
      register: command_result
      changed_when: command_result.stdout | d('none') == 'change'
      notify: change and mount swap

- name: "Swap: Disable swap and remove entry from /etc/fstab"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: ^\s*{{ fp_swap_md }}\s+(.*)$
    state: absent
    backup: "{{ fp_backup }}"
  notify: umount and delete swap
  when:
    - not fp_swap_enable | bool
    - fp_swap_md is defined

# EOF
