---
- name: Enable and start devfs
  listen: enable and start devfs
  ansible.builtin.service:
    name: devfs
    state: started
    enabled: true

- name: Disable and stop devfs
  listen: disable and stop devfs
  ansible.builtin.service:
    name: devfs
    state: stopped
    enabled: false

- name: Restart devfs
  listen: restart devfs
  ansible.builtin.service:
    name: devfs
    state: restarted
  when: fp_devfs_enabled | bool
