---
- name: Enable and start ntpd
  listen: enable and start ntpd
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true

- name: Disable and stop ntpd
  listen: disable and stop ntpd
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: false

- name: Restart ntpd
  listen: restart ntpd
  ansible.builtin.service:
    name: ntpd
    state: restarted
  when: fp_ntp_enable | bool
