---
- name: Enable and start qemu
  listen: enable and start qemu
  ansible.builtin.service:
    name: '"{{ fp_qemu_rcvar }}"'
    state: started
    enabled: true

- name: Disable and stop qemu
  listen: disable and stop qemu
  ansible.builtin.service:
    name: '"{{ fp_qemu_rcvar }}"'
    state: stopped
    enabled: false

- name: Restart qemu
  listen: restart qemu
  ansible.builtin.service:
    name: '"{{ fp_qemu_rcvar }}"'
    state: restarted
  when: fp_qemu_enabled | bool

- name: Reload qemu
  listen: reload qemu
  ansible.builtin.service:
    name: '"{{ fp_qemu_rcvar }}"'
    state: reloaded
  when: fp_qemu_enabled | bool
