---
- name: Enable and start snmpd
  listen: enable and start snmpd
  ansible.builtin.service:
    name: snmpd
    state: started
    enabled: true

- name: Disable and stop snmpd
  listen: disable and stop snmpd
  ansible.builtin.service:
    name: snmpd
    state: stopped
    enabled: false

- name: Restart snmpd
  listen: restart snmpd
  ansible.builtin.service:
    name: snmpd
    state: restarted
  when: fp_snmpd_enabled | bool
