---
- name: Enable and start syslogd
  listen: enable and start syslogd
  ansible.builtin.service:
    name: syslogd
    state: started
    enabled: true

- name: Disable and stop syslogd
  listen: disable and stop syslogd
  ansible.builtin.service:
    name: syslogd
    state: stopped
    enabled: false

- name: Restart syslogd
  listen: restart syslogd
  ansible.builtin.service:
    name: syslogd
    state: restarted
  when: fp_syslogd_enabled | bool

- name: Reload syslogd
  listen: reload syslogd
  ansible.builtin.service:
    name: syslogd
    state: reloaded
  when: fp_syslogd_enabled | bool
