---
- name: "{{ oi.label }}"
  ansible.builtin.lineinfile:
    dest: "{{ oi.dest | default('/etc/rc.conf') }}"
    regexp: ^\s*{{ item.key }}\s*=(.*)$
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ oi.conf }}"
  when: oi.when
  notify: "{{ oi.notify }}"

# EOF
